# Generated by Django 4.2.4 on 2023-11-30 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='city',
            new_name='City',
        ),
    ]
