# Generated by Django 4.2.4 on 2023-12-11 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_profile_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='wallet',
        ),
    ]
