# Generated by Django 4.2.4 on 2023-12-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_profile_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='credit_by_admin',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='new_wallet_balance',
            new_name='new_balance',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='initial_wallet_balance',
            new_name='previous_balance',
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(default=0.0, max_length=100),
            preserve_default=False,
        ),
    ]
