# Generated by Django 4.2.4 on 2024-01-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unitTax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
