# Generated by Django 4.2.4 on 2024-01-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_orderitem_unittax'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
