# Generated by Django 4.2.4 on 2024-02-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_remove_order_isprocessed_remove_order_processedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('sent', 'sent'), ('seen', 'seen'), ('processed', 'processed'), ('dispatched', 'dispatched'), ('delivered', 'delivered')], default='sent', max_length=20),
        ),
    ]
