# Generated by Django 4.2.4 on 2024-02-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_orderitem_delivery_alter_orderitem_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='delivery',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=0.0),
            preserve_default=False,
        ),
    ]
