# Generated by Django 4.2.4 on 2024-02-27 23:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_orderitem_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 2, 27, 23, 30, 26, 330327, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
