# Generated by Django 4.2.4 on 2024-02-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_orderitem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
